
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  buildmgr:
    if: github.repository == 'brondani/devtools'
    uses: brondani/devtools/.github/workflows/buildmgr.yml@main
    secrets: inherit
  packchk:
    uses: brondani/devtools/.github/workflows/packchk.yml@main
    secrets: inherit
  packgen:
    uses: brondani/devtools/.github/workflows/packgen.yml@main
    secrets: inherit
  projmgr:
    uses: brondani/devtools/.github/workflows/projmgr.yml@main
    secrets: inherit
