
name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  buildmgr:
    if: github.repository == 'brondani/devtools'
    uses: brondani/devtools/.github/workflows/buildmgr.yml@devtools-pack-ids-case-insensitive
    secrets: inherit
  packchk:
    needs: [buildmgr]
    uses: brondani/devtools/.github/workflows/packchk.yml@devtools-pack-ids-case-insensitive
    secrets: inherit
  packgen:
    needs: [packchk]
    uses: brondani/devtools/.github/workflows/packgen.yml@devtools-pack-ids-case-insensitive
    secrets: inherit
  projmgr:
    needs: [packgen]
    uses: brondani/devtools/.github/workflows/projmgr.yml@devtools-pack-ids-case-insensitive
    secrets: inherit
  svdconv:
    needs: [projmgr]
    uses: brondani/devtools/.github/workflows/svdconv.yml@devtools-pack-ids-case-insensitive
    secrets: inherit
  test_libs:
    needs: [svdconv]
    uses: brondani/devtools/.github/workflows/test_libs.yml@devtools-pack-ids-case-insensitive
